services:
  postgres:
    image: postgres:18.1
    container_name: skill-matcher-db
    environment:
      POSTGRES_DB: skillmatcher
      POSTGRES_USER: skillmatcher
      POSTGRES_PASSWORD: skillmatcher
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql

  mailhog:
    image: mailhog/mailhog:latest
    container_name: skill-matcher-mailhog
    ports:
      - "1025:1025"
      - "8025:8025"

  rabbitmq:
    image: rabbitmq:4-management
    container_name: skill-matcher-rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"

volumes:
  postgres-data:
